import type { Metadata } from "next";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { SubmitButton } from "@/components/submit-button";
import { requireHrmsAuth } from "@/lib/auth";
import { loadExitMasters } from "@/lib/exit-data";
import { saveExitDocumentTemplate, saveExitNotificationTemplate, saveExitPolicy, saveExitReason, saveExitTaskTemplate, saveExitWorkflow, toggleExitMaster } from "./actions";

export const metadata: Metadata = { title: "Exit masters" };
export const dynamic = "force-dynamic";
const recipientOptions = ["EMPLOYEE","REPORTING_MANAGER","HR_TEAM","HR_OWNER","TASK_OWNER"];

export default async function ExitSettingsPage({ searchParams }: { searchParams?: { error?: string; notice?: string } }) {
  const auth = await requireHrmsAuth("settings.manage");
  const masters = await loadExitMasters(auth); const p = masters.policy;
  return <AppShell auth={auth} active="Exit Masters">
    <PageHeader eyebrow="Configuration" title="Exit management masters" description="Control policies, reasons, approvals, tasks, document wording and email routing without code changes." action={<Link className="button secondary" href="/exits">Open exit register</Link>} />
    {searchParams?.error ? <div className="alert error" role="alert">{searchParams.error}</div> : null}{searchParams?.notice ? <div className="alert success" role="status">{searchParams.notice}</div> : null}
    <nav className="master-tabs"><a href="#policy">Policy</a><a href="#reasons">Reasons</a><a href="#workflow">Approvals</a><a href="#tasks">Tasks</a><a href="#documents">Documents</a><a href="#notifications">Notifications</a></nav>

    <MasterSection id="policy" title="Exit policy" description="Default timing, automation and document identity for this company."><form action={saveExitPolicy}><div className="form-grid">
      <Field label="Case prefix"><input name="case_number_prefix" defaultValue={p?.case_number_prefix ?? "EXIT"} maxLength={12} required /></Field>
      <Field label="Resignation notice days"><input name="resignation_notice_days" type="number" min="0" max="365" defaultValue={p?.resignation_notice_days ?? 30} required /></Field>
      <Field label="Termination notice days"><input name="termination_notice_days" type="number" min="0" max="365" defaultValue={p?.termination_notice_days ?? 0} required /></Field>
      <Field label="Settlement due after last day"><input name="settlement_due_days" type="number" min="0" max="365" defaultValue={p?.settlement_due_days ?? 2} required /></Field>
      <Field label="Authorised signatory"><input name="signatory_name" defaultValue={p?.signatory_name ?? ""} /></Field><Field label="Signatory title"><input name="signatory_title" defaultValue={p?.signatory_title ?? ""} /></Field>
      <Field label="Registered address" wide><textarea name="registered_address" defaultValue={p?.registered_address ?? ""} /></Field><Field label="Document footer" wide><input name="footer_text" defaultValue={p?.footer_text ?? ""} /></Field>
      <Check name="withdrawal_allowed" checked={p?.withdrawal_allowed !== false} title="Allow withdrawal requests" note="Employees may request withdrawal before closure." /><Check name="auto_create_tasks" checked={p?.auto_create_tasks !== false} title="Create tasks automatically" note="Copy active task masters into each new case." />
    </div><Actions label="Save exit policy" /></form></MasterSection>

    <MasterSection id="reasons" title="Exit reasons" description="Only employee-selectable resignation reasons appear in DropX One.">
      <form action={saveExitReason}><div className="master-entry-grid"><Field label="Scenario"><select name="scenario"><option value="resignation">Resignation</option><option value="termination">Termination</option><option value="other">Other</option></select></Field><Field label="Code"><input name="code" required /></Field><Field label="Name"><input name="name" required /></Field><Field label="Order"><input name="display_order" type="number" defaultValue="100" /></Field><Field label="Rehire default"><select name="default_rehire_eligible"><option value="unset">Not decided</option><option value="true">Eligible</option><option value="false">Not eligible</option></select></Field><label className="checkbox-row"><input name="employee_selectable" type="checkbox" /> Employee selectable</label><label className="checkbox-row"><input name="comment_required" type="checkbox" /> Comment required</label><SubmitButton className="button primary" pendingLabel="Adding reason…">Add reason</SubmitButton></div></form>
      <MasterTable headers={["Reason","Scenario","Employee option","Comment","Status","Action"]}>{masters.reasons.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{item.scenario}</td><td>{item.employee_selectable ? "Yes" : "No"}</td><td>{item.comment_required ? "Required" : "Optional"}</td><td><StatusPill value={item.is_active ? "active" : "inactive"} /></td><td><Toggle id={item.id} type="reason" active={item.is_active} /></td></tr>)}</MasterTable>
    </MasterSection>

    <MasterSection id="workflow" title="Approval workflow" description="Steps are copied into cases and enforced in numeric order.">
      <form action={saveExitWorkflow}><div className="master-entry-grid"><Field label="Scenario"><select name="scenario"><option value="resignation">Resignation</option><option value="termination">Termination</option><option value="all">All</option></select></Field><Field label="Code"><input name="code" required /></Field><Field label="Name"><input name="name" required /></Field><Field label="Order"><input name="step_order" type="number" defaultValue="10" required /></Field><Field label="Approver"><select name="approver_role"><option value="REPORTING_MANAGER">Reporting manager</option><option value="HR_MANAGER">HR manager</option><option value="HRMS_ADMIN">HRMS admin</option><option value="OWNER">Owner</option></select></Field><label className="checkbox-row"><input name="is_required" type="checkbox" defaultChecked /> Required</label><SubmitButton className="button primary" pendingLabel="Adding step…">Add step</SubmitButton></div></form>
      <MasterTable headers={["Step","Scenario","Order","Approver","Status","Action"]}>{masters.steps.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{item.scenario}</td><td>{item.step_order}</td><td>{item.approver_role.replaceAll("_", " ")}</td><td><StatusPill value={item.is_active ? "active" : "inactive"} /></td><td><Toggle id={item.id} type="workflow" active={item.is_active} /></td></tr>)}</MasterTable>
    </MasterSection>

    <MasterSection id="tasks" title="Task templates" description="Reusable handover, clearance, settlement and compliance checklists.">
      <form action={saveExitTaskTemplate}><div className="master-entry-grid"><Field label="Scenario"><select name="scenario"><option value="all">All</option><option value="resignation">Resignation</option><option value="termination">Termination</option></select></Field><Field label="Category"><select name="category"><option value="handover">Handover</option><option value="clearance">Clearance</option><option value="settlement">Settlement</option><option value="compliance">Compliance</option></select></Field><Field label="Code"><input name="code" required /></Field><Field label="Name"><input name="name" required /></Field><Field label="Owner"><select name="owner_role"><option value="EMPLOYEE">Employee</option><option value="REPORTING_MANAGER">Reporting manager</option><option value="HR_MANAGER">HR manager</option><option value="HRMS_ADMIN">HRMS admin</option><option value="OWNER">Owner</option></select></Field><Field label="Due offset"><input name="due_offset_days" type="number" defaultValue="0" /></Field><Field label="Order"><input name="display_order" type="number" defaultValue="100" /></Field><Field label="Instructions" wide><input name="instructions" /></Field><label className="checkbox-row"><input name="is_required" type="checkbox" defaultChecked /> Required</label><SubmitButton className="button primary" pendingLabel="Adding task…">Add task</SubmitButton></div></form>
      <MasterTable headers={["Task","Scenario","Category","Owner","Due","Status","Action"]}>{masters.tasks.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{item.scenario}</td><td>{item.category}</td><td>{item.owner_role.replaceAll("_", " ")}</td><td>{item.due_offset_days} days</td><td><StatusPill value={item.is_active ? "active" : "inactive"} /></td><td><Toggle id={item.id} type="task" active={item.is_active} /></td></tr>)}</MasterTable>
    </MasterSection>

    <MasterSection id="documents" title="Document templates" description="Edit the active PDF wording and placeholders. No source document upload is required."><div className="master-accordion">{masters.documents.map((item) => <details key={item.id}><summary><span><strong>{item.name}</strong><small>{item.document_type.replaceAll("_", " ")} · version {item.version}</small></span><StatusPill value={item.is_active ? "active" : "inactive"} /></summary><form action={saveExitDocumentTemplate}><input type="hidden" name="id" value={item.id} /><div className="form-grid"><Field label="Name"><input name="name" defaultValue={item.name} required /></Field><Field label="Stage"><select name="generation_stage" defaultValue={item.generation_stage}><option value="approval">Approval</option><option value="completion">Completion</option></select></Field><Field label="Title" wide><input name="title_template" defaultValue={item.title_template} required /></Field><Field label="Body" wide><textarea className="template-editor" name="body_template" defaultValue={item.body_template} required /></Field><label className="checkbox-row"><input name="is_active" type="checkbox" defaultChecked={item.is_active} /> Active</label></div><Actions label="Save document template" /></form></details>)}</div></MasterSection>

    <MasterSection id="notifications" title="Email notification rules" description="Roles resolve from reporting lines and HR access; optional custom emails remain in the database master."><div className="master-accordion">{masters.notifications.map((item) => <details key={item.id}><summary><span><strong>{item.name}</strong><small>{item.event_code.replaceAll("_", " ")}</small></span><StatusPill value={item.is_enabled ? "active" : "inactive"} /></summary><form action={saveExitNotificationTemplate}><input type="hidden" name="id" value={item.id} /><div className="form-grid"><RecipientChecks label="To roles" name="to_recipients" values={item.to_recipients} /><RecipientChecks label="CC roles" name="cc_recipients" values={item.cc_recipients} /><Field label="Custom To emails"><textarea name="custom_to_emails" defaultValue={item.custom_to_emails.join(", ")} /></Field><Field label="Custom CC emails"><textarea name="custom_cc_emails" defaultValue={item.custom_cc_emails.join(", ")} /></Field><Field label="Subject" wide><input name="subject_template" defaultValue={item.subject_template} required /></Field><Field label="Body" wide><textarea className="template-editor" name="body_template" defaultValue={item.body_template} required /></Field><label className="checkbox-row"><input name="is_enabled" type="checkbox" defaultChecked={item.is_enabled} /> Enabled</label></div><Actions label="Save notification rule" /></form></details>)}</div></MasterSection>
  </AppShell>;
}

function MasterSection({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <section className="panel master-section" id={id}><div className="panel-head"><div><h2>{title}</h2><p className="panel-subtitle">{description}</p></div></div><div className="panel-body">{children}</div></section>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`field${wide ? " wide" : ""}`}><span>{label}</span>{children}</label>; }
function Check({ name, checked, title, note }: { name: string; checked: boolean; title: string; note: string }) { return <label className="checkbox-card"><input name={name} type="checkbox" defaultChecked={checked} /><span><strong>{title}</strong><small>{note}</small></span></label>; }
function Actions({ label }: { label: string }) { return <div className="form-actions"><SubmitButton className="button primary" pendingLabel="Saving…">{label}</SubmitButton></div>; }
function MasterTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="table-wrap master-table"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Toggle({ id, type, active }: { id: string; type: string; active: boolean }) { return <form action={toggleExitMaster}><input type="hidden" name="id" value={id} /><input type="hidden" name="master_type" value={type} /><input type="hidden" name="next_active" value={active ? "false" : "true"} /><SubmitButton className="button secondary small" pendingLabel={active ? "Deactivating…" : "Activating…"}>{active ? "Deactivate" : "Activate"}</SubmitButton></form>; }
function RecipientChecks({ label, name, values }: { label: string; name: string; values: string[] }) { return <div className="field wide"><span>{label}</span><div className="recipient-grid">{recipientOptions.map((recipient) => <label className="checkbox-row" key={recipient}><input name={name} type="checkbox" value={recipient} defaultChecked={values.includes(recipient)} />{recipient.replaceAll("_", " ")}</label>)}</div></div>; }
