import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { EmployeeAvatar } from "@/components/employee-avatar";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { SubmitButton } from "@/components/submit-button";
import { requireHrmsAuth } from "@/lib/auth";
import { getExitCase } from "@/lib/exit-data";
import { can } from "@/lib/permissions";
import { approveSettlement, closeExitCase, generateExitDocuments, reviewExitApproval, saveSettlementItem, updateExitCase, updateExitTask } from "../actions";

export const metadata: Metadata = { title: "Exit case" };
export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });

export default async function ExitCasePage({ params, searchParams }: { params: { id: string }; searchParams?: { error?: string; notice?: string } }) {
  const auth = await requireHrmsAuth("exit.view");
  const detail = await getExitCase(auth, params.id);
  if (!detail) notFound();
  const { exitCase, approvals, tasks, settlement, documents, events, notifications } = detail;
  const employee = Array.isArray(exitCase.employees) ? exitCase.employees[0] : exitCase.employees;
  const station = Array.isArray(employee?.stations) ? employee.stations[0] : employee?.stations;
  const designation = Array.isArray(employee?.designations) ? employee.designations[0] : employee?.designations;
  const reason = Array.isArray(exitCase.hr_exit_reasons) ? exitCase.hr_exit_reasons[0] : exitCase.hr_exit_reasons;
  const manage = can(auth.permissions, "exit.manage");
  const approve = can(auth.permissions, "exit.approve");
  const earnings = settlement.filter((item) => item.item_type === "earning").reduce((sum, item) => sum + Number(item.amount), 0);
  const deductions = settlement.filter((item) => item.item_type === "deduction").reduce((sum, item) => sum + Number(item.amount), 0);
  const completedTasks = tasks.filter((task) => ["completed","waived"].includes(task.status)).length;
  const requiredPending = tasks.filter((task) => task.is_required && !["completed","waived"].includes(task.status)).length;
  const approvalPending = approvals.filter((item) => item.is_required && item.status !== "approved").length;
  return <AppShell auth={auth} active="Exit Management">
    <PageHeader eyebrow={exitCase.case_number} title={employee?.full_name ?? "Employee exit"} description={`${exitCase.scenario.replaceAll("_", " ")} · ${designation?.name ?? "Employee"} · ${station?.station_code ?? "No location"}`} action={<Link className="button secondary" href="/exits">Back to exits</Link>} />
    {searchParams?.error ? <div className="alert error" role="alert">{searchParams.error}</div> : null}
    {searchParams?.notice ? <div className="alert success" role="status">{searchParams.notice}</div> : null}
    <section className="panel employee-avatar-card">
      <EmployeeAvatar fullName={employee?.full_name ?? "Employee"} photoUrl={detail.employeePhotoUrl} size="large" />
      <div className="employee-avatar-card-copy"><p className="eyebrow">{employee?.employee_code ?? "-"}</p><h2>{employee?.full_name}</h2><p>{designation?.name ?? "Employee"} · {station?.station_name ?? station?.station_code ?? "No location"}</p><div className="employee-avatar-card-status"><StatusPill value={exitCase.status.replaceAll("_", " ")} /><StatusPill value={exitCase.current_stage.replaceAll("_", " ")} /></div></div>
      <div className="exit-progress"><strong>{completedTasks}/{tasks.length}</strong><span>tasks cleared</span></div>
    </section>
    <section className="grid stats-grid">
      <article className="card stat"><span className="stat-label">Requested date</span><strong className="stat-value compact">{exitCase.requested_last_working_date ?? "-"}</strong></article>
      <article className="card stat"><span className="stat-label">Approved last day</span><strong className="stat-value compact">{exitCase.approved_last_working_date ?? exitCase.effective_date ?? "-"}</strong></article>
      <article className="card stat"><span className="stat-label">Approvals pending</span><strong className="stat-value">{approvalPending}</strong></article>
      <article className="card stat"><span className="stat-label">Required tasks pending</span><strong className="stat-value">{requiredPending}</strong></article>
    </section>
    <section className="grid two-column exit-layout">
      <div className="grid">
        <article className="panel"><div className="panel-head"><div><h2>Case overview</h2><p className="panel-subtitle">Employee-submitted text is visible; confidential HR rationale remains inside HRMS.</p></div></div><div className="panel-body">
          <dl className="details-grid"><div className="detail"><dt>Source</dt><dd>{exitCase.source}</dd></div><div className="detail"><dt>Reason</dt><dd>{reason?.name ?? "-"}</dd></div><div className="detail"><dt>Notice days</dt><dd>{exitCase.notice_days}</dd></div><div className="detail"><dt>Personal email</dt><dd>{exitCase.personal_email ?? "-"}</dd></div><div className="detail"><dt>Rehire eligible</dt><dd>{exitCase.rehire_eligible == null ? "Not decided" : exitCase.rehire_eligible ? "Yes" : "No"}</dd></div><div className="detail"><dt>Settlement</dt><dd>{exitCase.settlement_status.replaceAll("_", " ")}</dd></div></dl>
          {exitCase.employee_reason ? <div className="case-note"><strong>Employee comments</strong><p>{exitCase.employee_reason}</p></div> : null}
          {exitCase.confidential_reason ? <div className="case-note confidential"><strong>Confidential HR rationale</strong><p>{exitCase.confidential_reason}</p></div> : null}
          {manage && !["closed","rejected"].includes(exitCase.status) ? <form action={updateExitCase} className="inline-form exit-update"><input type="hidden" name="case_id" value={exitCase.id} /><div className="field"><label htmlFor="approved_last_working_date">Approved last working date</label><input id="approved_last_working_date" name="approved_last_working_date" type="date" defaultValue={exitCase.approved_last_working_date ?? exitCase.effective_date ?? exitCase.requested_last_working_date ?? ""} /></div><div className="field"><label htmlFor="case_status">Case status</label><select id="case_status" name="status" defaultValue={exitCase.status}>{["approved","notice_period","clearance","on_hold","cancelled","withdrawn"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></div><SubmitButton className="button secondary" pendingLabel="Updating case…">Update case</SubmitButton></form> : null}
        </div></article>
        <article className="panel"><div className="panel-head"><div><h2>Approval workflow</h2><p className="panel-subtitle">Steps run in the order configured in Exit Masters.</p></div></div><div className="panel-body workflow-list">{approvals.length ? approvals.map((item) => <div className="workflow-item" key={item.id}><div className="workflow-index">{item.step_order}</div><div><strong>{item.step_name}</strong><p>{item.approver_role.replaceAll("_", " ")}{item.comments ? ` · ${item.comments}` : ""}</p></div><StatusPill value={item.status} />{approve && item.status === "pending" ? <form action={reviewExitApproval} className="workflow-action"><input type="hidden" name="case_id" value={exitCase.id} /><input type="hidden" name="approval_id" value={item.id} /><input name="comments" placeholder="Review comment" /><SubmitButton className="button primary small" name="decision" pendingLabel="Approving…" value="approved">Approve</SubmitButton><SubmitButton className="button danger small" name="decision" pendingLabel="Rejecting…" value="rejected">Reject</SubmitButton></form> : null}</div>) : <p className="muted">No approval steps configured for this scenario.</p>}</div></article>
        <article className="panel"><div className="panel-head"><div><h2>Handover and clearance</h2><p className="panel-subtitle">Every required task must be completed or explicitly waived before documents can be generated.</p></div></div><div className="table-wrap"><table><thead><tr><th>Task</th><th>Owner</th><th>Due</th><th>Status</th><th>Update</th></tr></thead><tbody>{tasks.length ? tasks.map((task) => <tr key={task.id}><td><strong>{task.name}</strong><div className="muted">{task.category} · {task.is_required ? "required" : "optional"}</div>{task.completion_note ? <div className="task-note">{task.completion_note}</div> : null}</td><td>{task.owner_role.replaceAll("_", " ")}</td><td>{task.due_date ?? "-"}</td><td><StatusPill value={task.status.replaceAll("_", " ")} /></td><td>{manage ? <form action={updateExitTask} className="task-form"><input type="hidden" name="case_id" value={exitCase.id} /><input type="hidden" name="task_id" value={task.id} /><select name="status" defaultValue={task.status}>{["pending","in_progress","completed","waived","blocked"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><input name="completion_note" placeholder="Completion / exception note" defaultValue={task.completion_note ?? ""} /><SubmitButton className="button secondary small" pendingLabel="Saving…">Save</SubmitButton></form> : "-"}</td></tr>) : <tr><td className="empty-cell" colSpan={5}>No clearance tasks were created.</td></tr>}</tbody></table></div></article>
        <article className="panel"><div className="panel-head"><div><h2>Full and final settlement</h2><p className="panel-subtitle">Values entered here populate the generated settlement statement.</p></div><StatusPill value={exitCase.settlement_status.replaceAll("_", " ")} /></div><div className="panel-body">
          {manage ? <form action={saveSettlementItem}><input type="hidden" name="case_id" value={exitCase.id} /><div className="settlement-entry"><div className="field"><label>Code</label><input name="code" placeholder="BONUS" required /></div><div className="field"><label>Label</label><input name="label" placeholder="Payable description" required /></div><div className="field"><label>Type</label><select name="item_type"><option value="earning">Earning</option><option value="deduction">Deduction</option></select></div><div className="field"><label>Amount</label><input name="amount" type="number" min="0" step="0.01" required /></div><SubmitButton className="button secondary" pendingLabel="Saving item…">Add / update</SubmitButton></div></form> : null}
          <div className="settlement-lines">{settlement.map((item) => <div key={item.id}><span>{item.label}<small>{item.code}</small></span><strong className={item.item_type === "deduction" ? "negative" : ""}>{item.item_type === "deduction" ? "−" : "+"}{money.format(Number(item.amount))}</strong></div>)}<div className="settlement-total"><span>Net settlement</span><strong>{money.format(earnings - deductions)}</strong></div></div>
          {manage ? <form action={approveSettlement} className="inline-actions"><input type="hidden" name="case_id" value={exitCase.id} /><SubmitButton className="button primary small" name="settlement_status" pendingLabel="Approving…" value="approved">Approve settlement</SubmitButton><SubmitButton className="button secondary small" name="settlement_status" pendingLabel="Marking paid…" value="paid">Mark paid</SubmitButton><SubmitButton className="button secondary small" name="settlement_status" pendingLabel="Updating…" value="not_applicable">Mark not applicable</SubmitButton></form> : null}
        </div></article>
        <article className="panel"><div className="panel-head"><div><h2>Generated documents</h2><p className="panel-subtitle">Documents are created from the active templates and live case data—no file upload is needed.</p></div>{manage ? <form action={generateExitDocuments}><input type="hidden" name="case_id" value={exitCase.id} /><SubmitButton className="button primary" pendingLabel="Generating documents…">Generate all documents</SubmitButton></form> : null}</div><div className="table-wrap"><table><thead><tr><th>Document</th><th>Version</th><th>Generated</th><th>Status</th><th>Download</th></tr></thead><tbody>{documents.length ? documents.map((document) => <tr key={document.id}><td><strong>{document.file_name}</strong><div className="muted">{document.document_type.replaceAll("_", " ")}</div></td><td>{document.template_version}</td><td>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(document.generated_at))}</td><td><StatusPill value={document.status} /></td><td><a className="button secondary small" href={`/exits/${exitCase.id}/documents/${document.id}`}>Download PDF</a></td></tr>) : <tr><td className="empty-cell" colSpan={5}>Documents will appear after every required approval, task and settlement step is complete.</td></tr>}</tbody></table></div>{manage && exitCase.status === "documents_ready" ? <div className="panel-body closure-bar"><div><strong>Final closure</strong><p>Closing marks the employee inactive in the shared employee master.</p></div><form action={closeExitCase}><input type="hidden" name="case_id" value={exitCase.id} /><SubmitButton className="button danger" pendingLabel="Closing exit…">Close exit and deactivate employee</SubmitButton></form></div> : null}</article>
      </div>
      <aside className="grid side-stack"><article className="panel"><div className="panel-head"><h2>Activity</h2></div><div className="panel-body"><ul className="activity-list compact-list">{events.length ? events.map((item) => <li key={item.id}><div><strong>{item.title}</strong><small>{item.actor_name ?? "System"}</small></div><time>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.created_at))}</time></li>) : <li className="muted">No activity recorded.</li>}</ul></div></article><article className="panel"><div className="panel-head"><h2>Email delivery</h2></div><div className="panel-body"><ul className="activity-list compact-list">{notifications.length ? notifications.map((item) => <li key={item.id}><div><strong>{item.event_code.replaceAll("_", " ")}</strong><small>{item.to_emails?.length ? item.to_emails.join(", ") : item.error_message ?? "No recipients"}</small></div><StatusPill value={item.status} /></li>) : <li className="muted">No notification attempts yet.</li>}</ul></div></article></aside>
    </section>
  </AppShell>;
}
